--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOOK" 
   (	"BOOKID" NUMBER(*,0), 
	"BOOKKIND" VARCHAR2(6 BYTE), 
	"BOOKTITLE" VARCHAR2(50 BYTE), 
	"BOOKPRICE" NUMBER(*,0), 
	"BOOKCOUNT" NUMBER(*,0), 
	"AUTHOR" VARCHAR2(40 BYTE), 
	"PUBCOM" VARCHAR2(40 BYTE), 
	"PUBDATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
